# ------------------- shyftnetwork Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: shyftnetwork-testnet
  name: shyftnetwork-testnet
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: shyftnetwork-testnet
  template:
    metadata:
      labels:
        k8s-app: shyftnetwork-testnet
    spec:
      containers:
      - name: shyftnetwork-testnet
        image: shyftnetwork/testnet:0.1
        command: [ "sh", "-c"]
        args:
        - 'cd /go/src/github.com/ShyftEthereum/go-empyrean &&
            ./wait-for.sh pg:5432 &&
            DBENV=docker export DBENV &&
            ./shyft-cli/initShyftGeth.sh &&
            ./shyft-cli/startShyftGeth.sh'
        ports:
          - containerPort: 8545
            name: http-8545
          - containerPort: 8546
            name: http-8546
          - containerPort: 31333
            name: 31333-tcp
            protocol: TCP
          - containerPort: 31333
            name: 31333-udp
            protocol: UDP
        env:
          - name: DBENV
            value: "docker"

---

# ------------------- shyftnetwork testnet Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: shyftnetwork-testnet
  name: shyftnetwork-testnet
spec:
  ports:
    - port: 8545
      targetPort: 8545
      name: http-8545
    - port: 8546
      targetPort: 8546
      name: http-8546
    - port: 31333
      targetPort: 31333
      name: tcp-31333
      protocol: TCP
    - port: 31333
      targetPort: 31333
      name: udp-31333
      protocol: UDP   
  selector:
    k8s-app:  shyftnetwork-testnet
  type: NodePort